### Numpy, Pandas, Matploblip nâng cao

In [1]:
import numpy as np
import pandas as pd

In [2]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
print(x)

[1 2 3 4 5 6 7]


In [3]:
data = [(1,2),(3,4),(5,6)]
mang = np.array(data)
print(mang)
print(mang[1,1])
print(mang[-1,1])
print(mang[-2,1])
print(mang[(1,2),:])
print(mang[1:3])
print(mang[0])
print(mang[:,0])
print(mang[0:2,0])
print(mang[(0,2),0])

[[1 2]
 [3 4]
 [5 6]]
4
6
4
[[3 4]
 [5 6]]
[[3 4]
 [5 6]]
[1 2]
[1 3 5]
[1 3]
[1 5]


In [4]:
## start, end, step
print(mang[::2,0])

[1 5]


In [5]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
mang = np.array(x)
print(mang)
print(mang[::,1]) ##2 6 10 14
print(mang[1:3,2]) ## 7 11
print(mang[[0,1,2],[3,2,1]])  ## 4 7 10
print(mang[3,::-1])   ## 16 15 14 13

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 2  6 10 14]
[ 7 11]
[ 4  7 10]
[16 15 14 13]


In [6]:
x = [
    [1,2,3],
    [4,5,6],
    [7,8,9]   
]
mang = np.array(x)
print(mang)

##lấy 4 5 6
print(mang[1])
##lấy 2 5
print(mang[:2,1])
##lấy 3 4
print(mang[[0,1],[2,0]])
##lấy 9 6 3
print(mang[::-1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[2 5]
[3 4]
[9 6 3]


In [7]:
x = [
    1,2,3,4,5,6,7,8,9,10
]
chan = [ num for num in x if num % 2 ==0 ]
print(x)
print(chan)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 4, 6, 8, 10]


In [8]:
x = np.ones((1,3,3))
print(x)

x1 = np.arange(3)
print(x1)
 
cong = x + x1
print(cong)
x1.shape



[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[0 1 2]
[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]


(3,)

In [15]:
## cho 1 bản np có 150 dòng 5 cột
import numpy as np
from sklearn.model_selection import train_test_split

# 1. Tạo mảng NumPy 150 x 5
np.random.seed(42)  # Đặt seed để kết quả nhất quán
data = np.random.rand(150, 5) * 100  # Tạo mảng ngẫu nhiên, nhân với 100 để tăng giá trị

# 2. Chia cột đầu tiên (chiều cao) thành x và cột cuối cùng (GPA) thành y
x = data[:, 0]  # Cột đầu tiên
y = data[:, -1]  # Cột cuối cùng

# 3. Chia dữ liệu x và y thành train/test (70:30)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# 4. Tạo tập dữ liệu không chồng chéo (loại bỏ giá trị trùng lặp trong x_train)
x_train_unique = np.unique(x_train)




In [16]:
# In kết quả
print("Mảng dữ liệu ban đầu:")
print(data)
print("\nBiến độc lập (x):", x)
print("\nBiến phụ thuộc (y):", y)
print("\nTập x_train:", x_train)
print("\nTập x_test:", x_test)
print("\nTập x_train không chồng chéo:", x_train_unique)

Mảng dữ liệu ban đầu:
[[37.45401188 95.07143064 73.19939418 59.86584842 15.60186404]
 [15.59945203  5.80836122 86.61761458 60.11150117 70.80725778]
 [ 2.05844943 96.99098522 83.24426408 21.23391107 18.18249672]
 [18.34045099 30.4242243  52.47564316 43.19450186 29.12291402]
 [61.18528947 13.94938607 29.21446485 36.63618433 45.60699842]
 [78.51759614 19.96737822 51.42344384 59.24145689  4.64504127]
 [60.75448519 17.05241237  6.5051593  94.88855373 96.56320331]
 [80.83973481 30.46137692  9.7672114  68.42330265 44.01524937]
 [12.20382348 49.51769101  3.43885211 90.93204021 25.87799816]
 [66.25222844 31.17110761 52.00680212 54.67102793 18.48544555]
 [96.95846278 77.51328234 93.94989416 89.48273504 59.78999788]
 [92.1874235   8.84925021 19.59828624  4.52272889 32.53303308]
 [38.86772897 27.13490318 82.87375092 35.67533267 28.09345097]
 [54.26960832 14.0924225  80.21969808  7.45506437 98.68869366]
 [77.22447693 19.87156815  0.55221171 81.54614285 70.68573438]
 [72.9007168  77.12703467  7.4044

In [17]:
#Bài tập tết
import numpy as np

# Khởi tạo ma trận 3x3 với giá trị mặc định là 99
matrix = np.full((3, 3), 99, dtype=object)

# Biến theo dõi lượt chơi (0 là 'O', 1 là 'X')
turn = 0  

while True:
    # Hiển thị ma trận hiện tại
    print("\nMa trận hiện tại:")
    for row in matrix:
        print(row)

    # Nhập vị trí từ người chơi
    try:
        row, col = map(int, input(f"Người chơi {'X' if turn == 1 else 'O'} nhập vị trí (dòng, cột) [0-2 0-2]: ").split())

        # Kiểm tra nếu nhập (0,0) thì trò chơi kết thúc
        if (row, col) == (0, 0):
            print("Bạn đã nhập (0,0). Trò chơi kết thúc!")
            break

        # Kiểm tra nếu nhập sai vị trí (ngoài phạm vi ma trận)
        if row not in [0, 1, 2] or col not in [0, 1, 2]:
            print("Vị trí không hợp lệ! Vui lòng nhập lại.")
            continue

        # Kiểm tra nếu ô đã có giá trị (không phải 99)
        if matrix[row, col] != 99:
            print("Ô này đã có người chọn! Vui lòng chọn ô khác.")
            continue

        # Điền vào ma trận theo lượt chơi
        matrix[row, col] = "X" if turn == 1 else "O"

        # Kiểm tra điều kiện thắng (ba ô liền kề giống nhau)
        for i in range(3):
            # Kiểm tra hàng, cột
            if (matrix[i, 0] == matrix[i, 1] == matrix[i, 2] != 99 or 
                matrix[0, i] == matrix[1, i] == matrix[2, i] != 99):
                print(f"Người chơi {'X' if turn == 1 else 'O'} thắng!")
                exit()

        # Kiểm tra hai đường chéo
        if (matrix[0, 0] == matrix[1, 1] == matrix[2, 2] != 99 or
            matrix[0, 2] == matrix[1, 1] == matrix[2, 0] != 99):
            print(f"Người chơi {'X' if turn == 1 else 'O'} thắng!")
            exit()

        # Chuyển lượt chơi
        turn = 1 - turn  

    except ValueError:
        print("Vui lòng nhập đúng định dạng số nguyên.")
    except IndexError:
        print("Chỉ số ngoài phạm vi! Nhập giá trị từ 0 đến 2.")

print("Trò chơi kết thúc!")


Ma trận hiện tại:
[99 99 99]
[99 99 99]
[99 99 99]
Vui lòng nhập đúng định dạng số nguyên.

Ma trận hiện tại:
[99 99 99]
[99 99 99]
[99 99 99]

Ma trận hiện tại:
[99 99 99]
[99 99 99]
[99 99 'O']

Ma trận hiện tại:
[99 99 99]
[99 99 'X']
[99 99 'O']
Bạn đã nhập (0,0). Trò chơi kết thúc!
Trò chơi kết thúc!


In [18]:
#Bài tập tết numpy
import numpy as np
from sklearn.model_selection import train_test_split

# 1. Tạo một mảng NumPy kích thước 150x5, chứa dữ liệu ngẫu nhiên
data = np.random.uniform(0, 10, (150, 5))

# 2. Chia mảng thành X (bốn cột đầu) và y (cột cuối)
X = data[:, :4]  # Chứa chiều cao, cân nặng, tuổi, lương
y = data[:, 4]   # Chứa GPA

# 3. Chia X và y thành tập huấn luyện (70%) và tập kiểm tra (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 4. Tạo 10 tập dữ liệu không chồng chéo từ X_train
num_subsets = 10
subset_size = len(X_train) // num_subsets
X_train_splits = [X_train[i * subset_size: (i + 1) * subset_size] for i in range(num_subsets)]

# Kiểm tra kích thước các tập dữ liệu
print("Kích thước X:", X.shape)
print("Kích thước y:", y.shape)
print("Kích thước X_train:", X_train.shape)
print("Kích thước X_test:", X_test.shape)
print(f"Tạo {num_subsets} tập con không chồng chéo từ X_train, mỗi tập có kích thước {subset_size}.")

Kích thước X: (150, 4)
Kích thước y: (150,)
Kích thước X_train: (105, 4)
Kích thước X_test: (45, 4)
Tạo 10 tập con không chồng chéo từ X_train, mỗi tập có kích thước 10.
